# Generated by Django 5.2.5 on 2025-09-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(blank=True, default="-", null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("age", models.IntegerField(default=0)),
                ("country", models.CharField(default="-", max_length=100)),
                ("birthplace", models.CharField(default="-", max_length=150)),
                ("plays", models.CharField(default="-", max_length=100)),
                ("coach", models.CharField(default="-", max_length=200)),
                ("turned_pro", models.IntegerField(default=0)),
                ("weight_lbs", models.IntegerField(default=0)),
                ("weight_kg", models.IntegerField(default=0)),
                ("height_cm", models.IntegerField(default=0)),
                ("height_feet", models.IntegerField(default=0)),
                ("height_inches", models.IntegerField(default=0)),
                ("career_high_rank", models.IntegerField(default=0)),
                ("career_high_rank_date", models.DateField(blank=True, null=True)),
                ("ytd_career_high_rank", models.IntegerField(default=0)),
                (
                    "ytd_career_high_rank_date",
                    models.CharField(default="-", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aces", models.IntegerField(default=0)),
                ("double_faults", models.IntegerField(default=0)),
                ("first_serve_pct", models.CharField(default="0", max_length=10)),
                (
                    "first_serve_points_won",
                    models.CharField(default="0", max_length=10),
                ),
                (
                    "second_serve_points_won",
                    models.CharField(default="0", max_length=10),
                ),
                ("break_points_faced", models.IntegerField(default=0)),
                ("break_points_saved", models.CharField(default="0", max_length=10)),
                ("service_games_played", models.IntegerField(default=0)),
                ("service_games_won", models.CharField(default="0", max_length=10)),
                (
                    "total_service_points_won",
                    models.CharField(default="0", max_length=10),
                ),
                (
                    "first_serve_return_points_won",
                    models.CharField(default="0", max_length=10),
                ),
                (
                    "second_serve_return_points_won",
                    models.CharField(default="0", max_length=10),
                ),
                ("break_points_opportunities", models.IntegerField(default=0)),
                (
                    "break_points_converted",
                    models.CharField(default="0", max_length=10),
                ),
                ("return_games_played", models.IntegerField(default=0)),
                ("return_games_won", models.CharField(default="0", max_length=10)),
                ("return_points_won", models.CharField(default="0", max_length=10)),
                ("total_points_won", models.CharField(default="0", max_length=10)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[("YTD", "Year To Date"), ("Career", "Career")],
                        max_length=10,
                    ),
                ),
                ("rank", models.IntegerField(default=0)),
                ("move", models.CharField(default="-", max_length=10)),
                ("wl_record", models.CharField(default="0 - 0", max_length=20)),
                ("titles", models.IntegerField(default=0)),
                ("prize_money", models.CharField(default="0", max_length=50)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "season")},
            },
        ),
        migrations.CreateModel(
            name="RankingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rank", models.IntegerField(default=0)),
                ("rank_change", models.CharField(default="-", max_length=10)),
                ("age", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("earn_drop", models.CharField(default="-", max_length=10)),
                ("tournaments", models.IntegerField(default=0)),
                ("dropping", models.CharField(default="-", max_length=10)),
                ("next_best", models.CharField(default="-", max_length=10)),
                ("country", models.CharField(default="-", max_length=10)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "rank"],
                "unique_together": {("player", "date")},
            },
        ),
    ]
