# Generated by Django 5.2.5 on 2025-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="career_high_rank",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="player",
            name="ytd_career_high_rank",
            field=models.CharField(default="-", max_length=10),
        ),
    ]
