# Generated by Django 5.2.5 on 2025-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_career_high_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="rank",
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="titles",
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="break_points_faced",
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="break_points_opportunities",
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="return_games_played",
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="service_games_played",
            field=models.CharField(default=0),
        ),
    ]
