# Generated by Django 5.2.5 on 2025-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_player_age_alter_playerrecord_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="career_high_rank_date",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="player",
            name="ytd_career_high_rank_date",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="aces",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="double_faults",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="age",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="points",
            field=models.CharField(default="-", max_length=10),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="rank",
            field=models.CharField(default="-", max_length=5),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="tournaments",
            field=models.CharField(default="-", max_length=10),
        ),
    ]
