# Generated by Django 5.2.5 on 2025-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_alter_player_career_high_rank_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="turned_pro",
            field=models.CharField(default="-", max_length=200),
        ),
    ]
