# Generated by Django 5.2.5 on 2025-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0005_alter_player_turned_pro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="height_cm",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="height_feet",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="height_inches",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight_kg",
            field=models.CharField(default="-", max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight_lbs",
            field=models.CharField(default="-", max_length=20),
        ),
    ]
