# Generated by Django 5.2.5 on 2025-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_alter_player_height_cm_alter_player_height_feet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="age",
        ),
        migrations.AlterField(
            model_name="player",
            name="birthplace",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="career_high_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="career_high_rank_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="coach",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="height_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="height_feet",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="height_inches",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="plays",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="turned_pro",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight_kg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="weight_lbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="ytd_career_high_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="ytd_career_high_rank_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="move",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="prize_money",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="titles",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerrecord",
            name="wl_record",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="aces",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="break_points_converted",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="break_points_faced",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="break_points_opportunities",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="break_points_saved",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="double_faults",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="first_serve_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="first_serve_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="first_serve_return_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="return_games_played",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="return_games_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="return_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="second_serve_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="second_serve_return_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="service_games_played",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="service_games_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="total_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="total_service_points_won",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="country",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="dropping",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="earn_drop",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="next_best",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="rank_change",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="rankingsnapshot",
            name="tournaments",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
