# Generated by Django 5.2.6 on 2025-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_remove_player_age_alter_player_birthplace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="ytd_career_high_rank",
        ),
        migrations.RemoveField(
            model_name="player",
            name="ytd_career_high_rank_date",
        ),
        migrations.AddField(
            model_name="player",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
