# Generated by Django 5.2.6 on 2025-09-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0008_remove_player_ytd_career_high_rank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="player",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="players/photos/"),
        ),
    ]
