# Generated by Django 5.2.6 on 2025-09-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0009_remove_player_photo_url_player_photo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RankingSnapshot",
            new_name="Ranking",
        ),
    ]
