# Generated by Django 5.2.6 on 2025-09-24 18:27

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0010_rename_rankingsnapshot_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=players.models.player_name_photo_path
            ),
        ),
    ]
