# Generated by Django 5.2.6 on 2025-10-12 13:47

import players.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0011_alter_player_id_alter_player_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="id",
            field=models.CharField(
                default=players.models.generate_player_id,
                editable=False,
                max_length=5,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
